### ISSUE TITLE
Update firstcal_metrics for IDR2.2

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#252] opened 2019-01-16 21:52 UTC
Right now firstcal metrics doesn't support dual-pol calfits files, which is what redcal will produce. See:
https://github.com/HERA-Team/hera_qm/blob/f7b13d9b2404cc4684ff36ee70fad2aa675b3a36/hera_qm/firstcal_metrics.py#L353

**Comment by adampbeardsley** [comment] 2019-01-17 19:15
This is a duplicate of #219

**Closed by adampbeardsley** 2019-01-17 19:15 UTC
